from web.template import CompiledTemplate, ForLoop, TemplateResult


# coding: utf-8
def index (res, i):
    __lineoffset__ = -4
    loop = ForLoop()
    self = TemplateResult(); extend_ = self.extend
    extend_([u'<!DOCTYPE html>\n'])
    extend_([u'<html>\n'])
    extend_([u'  <head>\n'])
    extend_([u'    <meta charset="utf-8">\n'])
    extend_([u'    <title>QunarCrawler</title>\n'])
    extend_([u'    <meta name="description" content="">\n'])
    extend_([u'    <meta name="author" content="">\n'])
    extend_([u'\n'])
    extend_([u'    <!-- Le styles -->\n'])
    extend_([u'    <link href="./static/css/bootstrap.css" rel="stylesheet">\n'])
    extend_([u'    <link href="./static/css/datepicker.css" rel="stylesheet">\n'])
    extend_([u'    <style>\n'])
    extend_([u'      body {\n'])
    extend_([u'        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */\n'])
    extend_([u'      }\n'])
    extend_([u'    </style>\n'])
    extend_([u'    <link href="./static/css/bootstrap-responsive.css" rel="stylesheet">\n'])
    extend_([u'\n'])
    extend_([u'    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->\n'])
    extend_([u'    <!--[if lt IE 9]>\n'])
    extend_([u'      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>\n'])
    extend_([u'    <![endif]-->\n'])
    extend_([u'\n'])
    extend_([u'    <!-- Le fav and touch icons -->\n'])
    extend_([u'    <link rel="shortcut icon" href="../assets/ico/favicon.ico">\n'])
    extend_([u'    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="./static/ico/apple-touch-icon-114-precomposed.png">\n'])
    extend_([u'    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="./static/ico/apple-touch-icon-72-precomposed.png">\n'])
    extend_([u'    <link rel="apple-touch-icon-precomposed" href="./static/ico/apple-touch-icon-57-precomposed.png">\n'])
    extend_([u'  </head>\n'])
    extend_([u'\n'])
    extend_([u'  <body>\n'])
    extend_([u'\n'])
    extend_([u'    <div class="navbar navbar-fixed-top">\n'])
    extend_([u'      <div class="navbar-inner">\n'])
    extend_([u'        <div class="container">\n'])
    extend_([u'          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">\n'])
    extend_([u'            <span class="icon-bar"></span>\n'])
    extend_([u'            <span class="icon-bar"></span>\n'])
    extend_([u'            <span class="icon-bar"></span>\n'])
    extend_([u'          </a>\n'])
    extend_([u'          <a class="brand" href="/">QunarCrawler</a>\n'])
    extend_([u'          <div class="nav-collapse">\n'])
    extend_([u'            <ul class="nav">\n'])
    extend_([u'              <li class="active"><a href="/">\u9996\u9875</a></li>\n'])
    extend_([u'              <li><a href="/log">log</a></li>\n'])
    extend_([u'              <!--<li><a href="#about">\u5173\u4e8e</a></li>-->\n'])
    extend_([u'              <!--<li><a href="#contact">\u8054\u7cfb</a></li>-->\n'])
    extend_([u'            </ul>\n'])
    extend_([u'          </div><!--/.nav-collapse -->\n'])
    extend_([u'        </div>\n'])
    extend_([u'      </div>\n'])
    extend_([u'    </div>\n'])
    extend_([u'\n'])
    extend_([u'    <div class="container">\n'])
    extend_([u'\n'])
    extend_([u'      <h2>\u4ec0\u4e48\u662fQunarCrawler?</h2>\n'])
    extend_([u'      <p></p>\n'])
    extend_([u'      <p>\n'])
    extend_([u'        \u987e\u540d\u601d\u4e49\uff0c\u901a\u4fd7\u5730\u8bf4\u5c31\u662f\u53bb\u54ea\u513f\u7f51\u7684\u722c\u866b\u3002:)\n'])
    extend_([u'      </p>\n'])
    extend_([u'\n'])
    extend_([u'      <p>\n'])
    extend_([u'        \u5f88\u591a\u4eba\u90fd\u6709\u8fc7\u8fd9\u6837\u7684\u60c5\u51b5\u3002\u60f3\u5b9a\u67d0\u5929\u7684\u98de\u673a\u7968\uff0c\u4f46\u662f\u4e0d\u77e5\u9053\u4ec0\u4e48\u65f6\u5019\u53bb\u4e70\u6700\u5408\u9002\u3002QunarCrawler\u5c31\u901a\u8fc7\u6293\u53d6\u5386\u53f2\u7684\u6570\u636e\uff0c\u8ba9\u5927\u5bb6\u53ef\u4ee5\u770b\u5230\u5bf9\u4e8e\u67d0\u5929\u7684\u673a\u7968\uff0c\u4e0d\u540c\u65f6\u5019\u53bb\u4e70\u7968\u4ef7\u662f\u5982\u4f55\u53d8\u5316\u7684\u3002\n'])
    extend_([u'      </p>\n'])
    extend_([u'        <form class="well" method="GET" action="">\n'])
    extend_([u'          <p>\n'])
    extend_([u'            <input type="text" class="input-small" placeholder="\u51fa\u53d1\u5730" name="from_place" \n'])
    if (i != None):
        extend_(['            ', u'value="', escape_(i.from_place, True), u'"\n'])
    extend_([u'            >\n'])
    extend_([u'            <input type="text" class="input-small" placeholder="\u76ee\u7684\u5730" name="to_place" \n'])
    if (i != None):
        extend_(['            ', u'value="', escape_(i.to_place, True), u'"\n'])
    extend_([u'            >\n'])
    extend_([u'          </p>\n'])
    extend_([u'          <p>\n'])
    extend_([u'            <input id="datepicker" class="input-small" type="text" placeholder="\u65e5\u671f" data-date-format="yyyy-mm-dd" name="date" \n'])
    if (i != None):
        extend_(['            ', u'value="', escape_(i.date, True), u'"\n'])
    extend_([u'            >\n'])
    extend_([u'          </p>\n'])
    extend_([u'          <p>\n'])
    extend_([u'            <select  name="search_type">\n'])
    extend_([u'              <option value="book"\n'])
    if (i != None and i.search_type == "book"):
        extend_(['              ', u'                      selected="selected"\n'])
    extend_([u'              >\u6211\u60f3\u770b\u8fd9\u5929\u7684\u673a\u7968\u54ea\u5929\u5b9a\u6700\u4fbf\u5b9c</option>\n'])
    extend_([u'              <option value="go"\n'])
    if (i != None and i.search_type == "go"):
        extend_(['              ', u'                      selected="selected"\n'])
    extend_([u'              >\u6211\u5728\u8fd9\u5929\u5b9a\u54ea\u5929\u673a\u7968\u6700\u4fbf\u5b9c</option>\n'])
    extend_([u'            </select>\n'])
    extend_([u'          </p>\n'])
    extend_([u'          <p>\n'])
    extend_([u'            <button type="submit" class="btn  btn-primary">\u6211\u8981\u67e5\u8be2!</button>\n'])
    extend_([u'          </p>\n'])
    extend_([u'          </form>\n'])
    extend_([u'\n'])
    if (res != None and res != []):
        extend_(['    ', u'<table class="table table-striped">\n'])
        extend_(['    ', u'    <tr>\n'])
        for e in loop.setup(res[:22]):
            extend_(['            ', u'<td>', escape_(eval('e.' + i.search_type + '_date'), True), u'</td>\n'])
        extend_(['    ', u'    </tr>\n'])
        extend_(['    ', u'    <tr>\n'])
        for e in loop.setup(res[:22]):
            extend_(['            ', u'<td>', escape_(e.price, True), u'</td>\n'])
        extend_(['    ', u'    </tr>\n'])
        for e in loop.setup(res[22:]):
            extend_(['            ', u'<td>', escape_(eval('e.' + i.search_type + '_date'), True), u'</td>\n'])
        extend_(['    ', u'    </tr>\n'])
        extend_(['    ', u'    <tr>\n'])
        for e in loop.setup(res[22:]):
            extend_(['            ', u'<td>', escape_(e.price, True), u'</td>\n'])
        extend_(['    ', u'    </tr>\n'])
        extend_(['    ', u'</table>\n'])
        extend_(['    ', u'\n'])
        extend_(['    ', u'        <div id="chart">\n'])
        extend_(['    ', u'        </div>\n'])
    elif (res == []):
        extend_(['    ', u'<div class="alert alert-error">\n'])
        extend_(['    ', u'          <h2>\u62b1\u6b49\uff0c\u6682\u65e0\u6570\u636e</h2>\n'])
        extend_(['    ', u'        </div>\n'])
    extend_([u'    </div> <!-- /container -->\n'])
    extend_([u'\n'])
    extend_([u'    <!-- Le javascript\n'])
    extend_([u'    ================================================== -->\n'])
    extend_([u'    <!-- Placed at the end of the document so the pages load faster -->\n'])
    extend_([u'    <script src="./static/js/jquery.min.js"></script>\n'])
    extend_([u'    <script src="./static/js/bootstrap.js"></script>\n'])
    extend_([u'    <script src="./static/js/bootstrap-datepicker.js"></script>\n'])
    extend_([u'        <script src="./static/js/highcharts.js"></script>\n'])
    extend_([u'    <script type="text/javascript">\n'])
    extend_([u'       ', u'$', u"('#datepicker').datepicker();\n"])
    if (res != None and res != []):
        extend_(['    ', u'$', u'(function () {\n'])
        extend_(['    ', u'     var chart;\n'])
        extend_(['    ', u'     ', u'$', u'(document).ready(function() {\n'])
        extend_(['    ', u'         chart = new Highcharts.Chart({\n'])
        extend_(['    ', u'             chart: {\n'])
        extend_(['    ', u"                 renderTo: 'chart',\n"])
        extend_(['    ', u"                 type: 'line',\n"])
        extend_(['    ', u'                 marginRight: 130,\n'])
        extend_(['    ', u'                 marginBottom: 25\n'])
        extend_(['    ', u'             },\n'])
        extend_(['    ', u'             title: {\n'])
        extend_(['    ', u"                 text: '\u4ef7\u683c\u8d70\u52bf\u56fe',\n"])
        extend_(['    ', u'                 x: -20 //center\n'])
        extend_(['    ', u'             },\n'])
        extend_(['    ', u'             xAxis: {\n'])
        extend_(['    ', u"                 categories: ['", escape_(eval("res[0]." + i.search_type + "_date"), True), u"'\n"])
        for e in loop.setup(res[1:]):
            extend_(['                 ', u",'", escape_(eval("e." + i.search_type + "_date"), True), u"'\n"])
        extend_(['    ', u'             ]\n'])
        extend_(['    ', u'             },\n'])
        extend_(['    ', u'             yAxis: {\n'])
        extend_(['    ', u'                 title: {\n'])
        extend_(['    ', u"                     text: '\u4ef7\u683c (\uffe5)'\n"])
        extend_(['    ', u'                 },\n'])
        extend_(['    ', u'                 plotLines: [{\n'])
        extend_(['    ', u'                     value: 0,\n'])
        extend_(['    ', u'                     width: 1,\n'])
        extend_(['    ', u"                     color: '#808080'\n"])
        extend_(['    ', u'                 }]\n'])
        extend_(['    ', u'             },\n'])
        extend_(['    ', u'             tooltip: {\n'])
        extend_(['    ', u'                 formatter: function() {\n'])
        extend_(['    ', u"                         return '<b>'+ this.series.name +'</b><br/>'+\n"])
        extend_(['    ', u"                         this.x +': \uffe5'+ this.y;\n"])
        extend_(['    ', u'                 }\n'])
        extend_(['    ', u'             },\n'])
        extend_(['    ', u'             legend: {\n'])
        extend_(['    ', u"                 layout: 'vertical',\n"])
        extend_(['    ', u"                 align: 'right',\n"])
        extend_(['    ', u"                 verticalAlign: 'top',\n"])
        extend_(['    ', u'                 x: -10,\n'])
        extend_(['    ', u'                 y: 100,\n'])
        extend_(['    ', u'                 borderWidth: 0\n'])
        extend_(['    ', u'             },\n'])
        extend_(['    ', u'             series: [{\n'])
        extend_(['    ', u"                 name: '\u8d70\u52bf',\n"])
        extend_(['    ', u'                 data: [', escape_(res[0].price, True), u'\n'])
        for e in loop.setup(res[1:]):
            extend_(['                 ', u',', escape_(e.price, True), u'\n'])
        extend_(['    ', u'             ]\n'])
        extend_(['    ', u'             }]\n'])
        extend_(['    ', u'         });\n'])
        extend_(['    ', u'     });\n'])
        extend_(['    ', u'\n'])
        extend_(['    ', u' });\n'])
    extend_([u'    </script>\n'])
    extend_([u'  </body>\n'])
    extend_([u'</html>\n'])
    extend_([u'\n'])

    return self

index = CompiledTemplate(index, 'templates/index.html')
join_ = index._join; escape_ = index._escape

# coding: utf-8
def log (logs):
    __lineoffset__ = -4
    loop = ForLoop()
    self = TemplateResult(); extend_ = self.extend
    extend_([u'<!DOCTYPE html>\n'])
    extend_([u'<html>\n'])
    extend_([u'  <head>\n'])
    extend_([u'    <meta charset="utf-8">\n'])
    extend_([u'    <title>QunarCrawler</title>\n'])
    extend_([u'    <meta name="description" content="">\n'])
    extend_([u'    <meta name="author" content="">\n'])
    extend_([u'\n'])
    extend_([u'    <!-- Le styles -->\n'])
    extend_([u'    <link href="./static/css/bootstrap.css" rel="stylesheet">\n'])
    extend_([u'    <link href="./static/css/datepicker.css" rel="stylesheet">\n'])
    extend_([u'    <style>\n'])
    extend_([u'      body {\n'])
    extend_([u'        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */\n'])
    extend_([u'      }\n'])
    extend_([u'    </style>\n'])
    extend_([u'    <link href="./static/css/bootstrap-responsive.css" rel="stylesheet">\n'])
    extend_([u'\n'])
    extend_([u'    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->\n'])
    extend_([u'    <!--[if lt IE 9]>\n'])
    extend_([u'      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>\n'])
    extend_([u'    <![endif]-->\n'])
    extend_([u'\n'])
    extend_([u'    <!-- Le fav and touch icons -->\n'])
    extend_([u'    <link rel="shortcut icon" href="../assets/ico/favicon.ico">\n'])
    extend_([u'    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="./static/ico/apple-touch-icon-114-precomposed.png">\n'])
    extend_([u'    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="./static/ico/apple-touch-icon-72-precomposed.png">\n'])
    extend_([u'    <link rel="apple-touch-icon-precomposed" href="./static/ico/apple-touch-icon-57-precomposed.png">\n'])
    extend_([u'  </head>\n'])
    extend_([u'\n'])
    extend_([u'  <body>\n'])
    extend_([u'\n'])
    extend_([u'    <div class="navbar navbar-fixed-top">\n'])
    extend_([u'      <div class="navbar-inner">\n'])
    extend_([u'        <div class="container">\n'])
    extend_([u'          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">\n'])
    extend_([u'            <span class="icon-bar"></span>\n'])
    extend_([u'            <span class="icon-bar"></span>\n'])
    extend_([u'            <span class="icon-bar"></span>\n'])
    extend_([u'          </a>\n'])
    extend_([u'          <a class="brand" href="/">QunarCrawler</a>\n'])
    extend_([u'          <div class="nav-collapse">\n'])
    extend_([u'            <ul class="nav">\n'])
    extend_([u'              <li><a href="/">\u9996\u9875</a></li>\n'])
    extend_([u'              <li class="active"><a href="/log">log</a></li>\n'])
    extend_([u'              <!--<li><a href="#about">\u5173\u4e8e</a></li>-->\n'])
    extend_([u'              <!--<li><a href="#contact">\u8054\u7cfb</a></li>-->\n'])
    extend_([u'            </ul>\n'])
    extend_([u'          </div><!--/.nav-collapse -->\n'])
    extend_([u'        </div>\n'])
    extend_([u'      </div>\n'])
    extend_([u'    </div>\n'])
    extend_([u'\n'])
    extend_([u'    <div class="container">\n'])
    extend_([u'\n'])
    extend_([u'      <h2>log</h2>\n'])
    extend_([u'      <p>\n'])
    for log in loop.setup(logs):
        extend_(['        ', u'<h3>', escape_(log.date, True), u'</h3>\n'])
        extend_(['        ', u'<ul>', escape_(log.log, False), u'</ul> \n'])
    extend_([u'      </p>\n'])
    extend_([u'    </div> <!-- /container -->\n'])
    extend_([u'\n'])
    extend_([u'    <!-- Le javascript\n'])
    extend_([u'    ================================================== -->\n'])
    extend_([u'    <!-- Placed at the end of the document so the pages load faster -->\n'])
    extend_([u'    <script src="./static/js/jquery.min.js"></script>\n'])
    extend_([u'    <script src="./static/js/bootstrap.js"></script>\n'])
    extend_([u'    <script src="./static/js/bootstrap-datepicker.js"></script>\n'])
    extend_([u'    <script type="text/javascript">\n'])
    extend_([u'       ', u'$', u"('#datepicker').datepicker(format = 'yyyy-mm-dd')\n"])
    extend_([u'    </script>\n'])
    extend_([u'  </body>\n'])
    extend_([u'</html>\n'])
    extend_([u'\n'])

    return self

log = CompiledTemplate(log, 'templates/log.html')
join_ = log._join; escape_ = log._escape

